@host = http://krakend-rocky96.labscloudhibirds.site
POST {{host}}/api/v1/conditional-operation
X-JWT: eyJhbGciOiJIUzI1NiIsImtpZCI6ImtleTEifQ.eyJzdWIiOiJzaGV5bGEifQ.L4oztPoJpWbLZ7Fb6Z26BrTBSk3qZCJxEzEl4HLOHQ8
Content-Type: application/json

{
  "any": "data"
}
### Health Check
GET {{host}}/api/v1/health-check
X-Forwarded-For: 10.0.0.12